### ISSUE TITLE
ページングに対応してない？

### ISSUE THREAD

**Issue by PharaohKJ** [PharaohKJ/holiday_doctor_scraper#2]
http://i-search.pref.ishikawa.jp/toban/index.php?a=3

の情報はありますが

http://i-search.pref.ishikawa.jp/toban/index.php?p=2&a=3

の情報がないようです。ウェブページでは下段の「次へ」をクリックすれば次のページになります。

**Comment by PharaohKJ** [comment]
@watari3 さんご確認お願いします。( fork 先に issue がなかったのでココに書いちゃいました )

**Comment by watari3** [comment]
URLの補正処理が抜けていましたので修正いたしました。

https://github.com/watari3/holiday_doctor_scraper に修正対応版をpushしてあります。

**Comment by PharaohKJ** [comment]
@watari3 プルリクしてください。

まぁ今回はこっちでやっちゃいました。すみません。

**Comment by PharaohKJ** [comment]
@watari3 ページング処理はOKのようですが同じ「科」が重複するとまともに動きませんね。
https://github.com/50river/holiday_doctor を開いて、上の内科、下の内科、を選んでみてください。

ビュー側にあるサンプルデータを元にどう動くか確認したほうがよさそうですね。

いったんここではクローズします。
